import React from 'react';
import { useSettingsStore } from '../store/useSettingsStore';
import { useAIDebugStore } from '../store/useAIDebugStore';
import { AlertTriangle, Cpu, Zap, Activity, WifiOff, Timer } from 'lucide-react';

// The doc §12 status set. Each maps to a label, color, and icon.
export const AI_STATUS = {
  GENERATING: { key: 'generating', label: 'AI Generation Active', color: '#4338ca', icon: Activity },
  CONNECTED: { key: 'connected', label: 'Gemini Connected', color: '#10b981', icon: Zap },
  SIMULATOR: { key: 'simulator', label: 'Simulator Mode', color: '#f59e0b', icon: Cpu },
  RATE_LIMITED: { key: 'rate_limited', label: 'Rate Limited', color: '#ef4444', icon: Timer },
  API_ERROR: { key: 'api_error', label: 'API Error', color: '#ef4444', icon: WifiOff },
  FALLBACK: { key: 'fallback', label: 'Fallback Active', color: '#f59e0b', icon: AlertTriangle },
};

/**
 * Returns the current AI mode as a simple descriptor object.
 * Use this hook anywhere you need to know if real AI is running.
 */
export function useAIMode() {
  const { aiModeEnabled, apiKey } = useSettingsStore();
  const generationSources = useAIDebugStore(s => s.generationSources);
  const activeGenerations = useAIDebugStore(s => s.activeGenerations);
  const lastError = useAIDebugStore(s => s.lastError);

  const isGeminiConfigured = aiModeEnabled && !!apiKey?.trim();

  // If at least one agent used Gemini successfully, we've confirmed live AI
  const hasLiveOutput = Object.values(generationSources).some(s => s === 'Gemini');
  const hasFallbackOutput = Object.values(generationSources).some(s => s === 'Fallback');

  const mode = isGeminiConfigured ? 'Gemini' : 'Simulator';
  const reason = !aiModeEnabled
    ? 'AI Mode is disabled in Settings'
    : !apiKey?.trim()
    ? 'Gemini API Key Missing'
    : null;

  // Live status per doc §12, most specific first
  let status;
  if (!isGeminiConfigured) status = AI_STATUS.SIMULATOR;
  else if (activeGenerations > 0) status = AI_STATUS.GENERATING;
  else if (lastError?.kind === 'rate_limit') status = AI_STATUS.RATE_LIMITED;
  else if (lastError?.kind === 'api_error') status = AI_STATUS.API_ERROR;
  else if (hasFallbackOutput) status = AI_STATUS.FALLBACK;
  else status = AI_STATUS.CONNECTED;

  return { mode, reason, status, lastError, isGeminiConfigured, hasLiveOutput, hasFallbackOutput };
}

const BANNER_MESSAGES = {
  simulator: {
    title: 'Running in Simulator Mode',
    body: (reason) => <>Gemini AI is not configured. The platform is currently using <strong>fallback templates</strong>, not real AI.{reason && <span style={{ color: 'var(--text-muted)', marginLeft: '4px' }}>— {reason}.</span>}</>
  },
  rate_limited: {
    title: 'Gemini Rate Limited',
    body: () => <>The Gemini API is rejecting requests due to rate limits. Recent output may have used <strong>fallback templates</strong>. Wait a moment and try again.</>
  },
  api_error: {
    title: 'Gemini API Error',
    body: (reason, lastError) => <>The last Gemini request failed{lastError?.message ? <>: <strong>{lastError.message}</strong></> : ''}. Check your API key and connection.</>
  },
  fallback: {
    title: 'Fallback Content Active',
    body: () => <>Some sections were generated by the <strong>Fallback Simulator</strong> because AI generation failed. They are not AI-generated — check the section source badges.</>
  }
};

/**
 * Prominent banner shown whenever real AI is not (fully) active (doc §12).
 */
export function AIStatusBanner() {
  const { reason, status, lastError } = useAIMode();

  const message = BANNER_MESSAGES[status.key];
  if (!message) return null; // Connected / Generating need no warning banner

  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: '12px',
      padding: '14px 16px', borderRadius: '10px', marginBottom: '1.5rem',
      background: `${status.color}14`,
      border: `1px solid ${status.color}66`,
    }}>
      <AlertTriangle size={18} color={status.color} style={{ flexShrink: 0, marginTop: '1px' }} />
      <div style={{ fontSize: '0.85rem', lineHeight: 1.5 }}>
        <div style={{ fontWeight: 700, color: status.color, marginBottom: '2px' }}>
          {message.title}
        </div>
        <div style={{ color: 'var(--text-secondary)' }}>
          {message.body(reason, lastError)}
        </div>
      </div>
    </div>
  );
}

/**
 * Small inline badge used in the Dashboard header / Blueprint sections.
 */
export function AIModeBadge({ style }) {
  const { reason, status } = useAIMode();
  const Icon = status.icon;

  return (
    <div
      title={reason || status.label}
      style={{
        display: 'inline-flex', alignItems: 'center', gap: '5px',
        padding: '3px 10px', borderRadius: '20px', fontSize: '0.72rem', fontWeight: 700,
        background: `${status.color}1f`,
        border: `1px solid ${status.color}59`,
        color: status.color,
        cursor: 'default',
        ...style
      }}
    >
      <Icon size={11} />
      {status.label}
    </div>
  );
}

/**
 * Confidence label that changes wording based on whether real AI ran.
 */
export function ConfidenceLabel({ value, agentRole }) {
  const generationSources = useAIDebugStore(s => s.generationSources);
  const source = generationSources[agentRole];

  const isSimulator = source === 'Fallback' || source === null;

  const label = isSimulator ? 'Template Quality' : 'AI Confidence';
  const color = value === 'High'
    ? 'var(--success)'
    : value === 'Medium'
    ? 'var(--warning)'
    : 'var(--danger)';

  return (
    <div style={{
      fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '4px',
      background: 'rgba(0,0,0,0.2)', padding: '2px 8px', borderRadius: '12px'
    }}>
      <span style={{ color: 'var(--text-muted)' }}>{label}:</span>
      <span style={{ color, fontWeight: 500 }}>{value}</span>
      {isSimulator && (
        <span title="This output was generated by the Fallback Simulator, not Gemini AI."
          style={{ color: '#f59e0b', fontSize: '0.65rem', marginLeft: '2px' }}>⚠</span>
      )}
    </div>
  );
}
