import React from 'react';
import { AlertTriangle, X } from 'lucide-react';
import { useAIMode } from './aiStatusModel';

const BANNER_MESSAGES = {
  simulator: {
    title: 'Running in Simulator Mode',
    body: (reason) => <>Gemini AI is not configured. The platform is currently using <strong>fallback templates</strong>, not real AI.{reason && <span style={{ color: 'var(--text-muted)', marginLeft: '4px' }}>— {reason}.</span>}</>
  },
  rate_limited: {
    title: 'Gemini Rate Limited',
    body: () => <>The Gemini API is rejecting requests due to rate limits. Recent output may have used <strong>fallback templates</strong>. Wait a moment and try again.</>
  },
  api_error: {
    title: 'Gemini API Error',
    body: (reason, lastError) => <>The last Gemini request failed{lastError?.message ? <>: <strong>{lastError.message}</strong></> : ''}. Check your API key and connection.</>
  },
  fallback: {
    title: 'Fallback Content Active',
    body: () => <>Some sections were generated by the <strong>Fallback Simulator</strong> because AI generation failed. They are not AI-generated — check the section source badges.</>
  }
};

/**
 * Prominent banner shown whenever real AI is not (fully) active (doc §12).
 */
export function AIStatusBanner({ floating = false, dismissible = false }) {
  const { reason, status, lastError } = useAIMode();
  const [dismissedNotification, setDismissedNotification] = React.useState(null);

  const message = BANNER_MESSAGES[status.key];
  const notificationId = `${status.key}:${lastError?.timestamp || ''}`;
  if (!message || dismissedNotification === notificationId) return null; // Connected / Generating need no warning banner

  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: '12px',
      padding: '14px 16px', borderRadius: '10px', marginBottom: floating ? 0 : '1.5rem',
      background: `${status.color}14`,
      border: `1px solid ${status.color}66`,
      ...(floating ? {
        position: 'fixed',
        top: '16px',
        right: '16px',
        width: 'min(520px, calc(100vw - 32px))',
        zIndex: 1000,
        boxShadow: '0 12px 32px rgba(0, 0, 0, 0.45)',
        backdropFilter: 'blur(14px)',
      } : {}),
    }}>
      <AlertTriangle size={18} color={status.color} style={{ flexShrink: 0, marginTop: '1px' }} />
      <div style={{ flex: 1, minWidth: 0, fontSize: '0.85rem', lineHeight: 1.5, overflowWrap: 'anywhere' }}>
        <div style={{ fontWeight: 700, color: status.color, marginBottom: '2px' }}>
          {message.title}
        </div>
        <div style={{ color: 'var(--text-secondary)' }}>
          {message.body(reason, lastError)}
        </div>
      </div>
      {dismissible && (
        <button
          type="button"
          aria-label="Dismiss notification"
          title="Dismiss"
          onClick={() => setDismissedNotification(notificationId)}
          style={{
            display: 'flex',
            flexShrink: 0,
            padding: '2px',
            border: 0,
            background: 'transparent',
            color: 'var(--text-muted)',
            cursor: 'pointer',
          }}
        >
          <X size={16} />
        </button>
      )}
    </div>
  );
}

/**
 * Small inline badge used in the Dashboard header / Blueprint sections.
 */
export function AIModeBadge({ style }) {
  const { reason, status } = useAIMode();
  const Icon = status.icon;

  return (
    <div
      title={reason || status.label}
      style={{
        display: 'inline-flex', alignItems: 'center', gap: '5px',
        padding: '3px 10px', borderRadius: '20px', fontSize: '0.72rem', fontWeight: 700,
        background: `${status.color}1f`,
        border: `1px solid ${status.color}59`,
        color: status.color,
        cursor: 'default',
        ...style
      }}
    >
      <Icon size={11} />
      {status.label}
    </div>
  );
}
