import React from 'react';
import { AlertTriangle } from 'lucide-react';
import { useAIMode } from './aiStatusModel';

const BANNER_MESSAGES = {
  simulator: {
    title: 'Running in Simulator Mode',
    body: (reason) => <>Gemini AI is not configured. The platform is currently using <strong>fallback templates</strong>, not real AI.{reason && <span style={{ color: 'var(--text-muted)', marginLeft: '4px' }}>— {reason}.</span>}</>
  },
  rate_limited: {
    title: 'Gemini Rate Limited',
    body: () => <>The Gemini API is rejecting requests due to rate limits. Recent output may have used <strong>fallback templates</strong>. Wait a moment and try again.</>
  },
  api_error: {
    title: 'Gemini API Error',
    body: (reason, lastError) => <>The last Gemini request failed{lastError?.message ? <>: <strong>{lastError.message}</strong></> : ''}. Check your API key and connection.</>
  },
  fallback: {
    title: 'Fallback Content Active',
    body: () => <>Some sections were generated by the <strong>Fallback Simulator</strong> because AI generation failed. They are not AI-generated — check the section source badges.</>
  }
};

/**
 * Prominent banner shown whenever real AI is not (fully) active (doc §12).
 */
export function AIStatusBanner() {
  const { reason, status, lastError } = useAIMode();

  const message = BANNER_MESSAGES[status.key];
  if (!message) return null; // Connected / Generating need no warning banner

  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: '12px',
      padding: '14px 16px', borderRadius: '10px', marginBottom: '1.5rem',
      background: `${status.color}14`,
      border: `1px solid ${status.color}66`,
    }}>
      <AlertTriangle size={18} color={status.color} style={{ flexShrink: 0, marginTop: '1px' }} />
      <div style={{ fontSize: '0.85rem', lineHeight: 1.5 }}>
        <div style={{ fontWeight: 700, color: status.color, marginBottom: '2px' }}>
          {message.title}
        </div>
        <div style={{ color: 'var(--text-secondary)' }}>
          {message.body(reason, lastError)}
        </div>
      </div>
    </div>
  );
}

/**
 * Small inline badge used in the Dashboard header / Blueprint sections.
 */
export function AIModeBadge({ style }) {
  const { reason, status } = useAIMode();
  const Icon = status.icon;

  return (
    <div
      title={reason || status.label}
      style={{
        display: 'inline-flex', alignItems: 'center', gap: '5px',
        padding: '3px 10px', borderRadius: '20px', fontSize: '0.72rem', fontWeight: 700,
        background: `${status.color}1f`,
        border: `1px solid ${status.color}59`,
        color: status.color,
        cursor: 'default',
        ...style
      }}
    >
      <Icon size={11} />
      {status.label}
    </div>
  );
}
